Update arg_helper.py
The original script would lead to `TypeError: load() missing 1 required positional argument: 'Loader'`, update to current one to avoid this error